{{- if eq (include "logginghelm.installLO" .) "true" }}
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: loki-operator
  namespace: openshift-operators-redhat
  annotations:
    olm.providedAPIs: AlertingRule.v1.loki.grafana.com,LokiStack.v1.loki.grafana.com,RecordingRule.v1.loki.grafana.com,RulerConfig.v1.loki.grafana.com
  labels:
    app: {{ template "logginghelm.name" . }}
    chart: {{ template "logginghelm.chart" . }}
    release: {{ .Release.Name }}
spec:
  upgradeStrategy: Default
{{- end }}