apiVersion: addon.open-cluster-management.io/v1alpha1
kind: AddOnDeploymentConfig
metadata:
  name: multicluster-observability-addon
  namespace: open-cluster-management-observability
spec:
  customizedVariables:
  # Operator Subscription Channels
  - name: openshiftLoggingChannel
    value: stable-6.1
  - name: hubHostname
    value: jmarcalaws2411297.devcluster.openshift.com
  # Platform Observability
  - name: platformLogsStorage
    value: lokistacks.v1.loki.grafana.io
