{{- if .Values.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: tracing-auth
  namespace: open-cluster-management-observability
  labels:
    mcoa.openshift.io/signal: tracing
data:
  otlp: mTLS
{{- end }}
