apiVersion: v1
kind: Secret
metadata:
  name: mtls-spoke-hub
  namespace: openshift-logging
  labels:
    app: {{ template "lokihelm.name" . }}
    chart: {{ template "lokihelm.chart" . }}
    release: {{ .Release.Name }}
data:
  'tls.crt': {{ "cert" | b64enc }}
  'tls.key': {{ "key" | b64enc }}
  'ca-bundle.crt': {{ "ca-bundle" | b64enc }}
