spokeClusters:
- spoke-1

addonInstallNamespace: open-cluster-management-agent-addon

metrics:
  enabled: true

logging:
  enabled: true
  
  outputs:
    - name: cw-infra
      type: cloudwatch
    - name: loki-infra
      type: loki
      url: https://my-loki.app

tracing:
  enabled: false
  
  outputs:
    - type: jaeger
    - type: otlp
      url: https://otlp.app 