{{- if and .Values.logging.enabled .Values.logging.loki.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: hub-lokistack-s3-credentials
  namespace: openshift-logging
type: Opaque
data:
  endpoint: {{ .Values.logging.loki.s3Bucket.endpoint | b64enc }}
  region: {{ .Values.logging.loki.s3Bucket.region | b64enc }}
  access_key_id: {{ .Values.logging.aws.keyID | b64enc }}
  access_key_secret: {{ .Values.logging.aws.keySecret | b64enc }}
  bucketnames: {{ .Values.logging.loki.s3Bucket.bucketnames | b64enc }}
{{- end }}