apiVersion: v1
kind: Namespace
metadata:
  name: openshift-operators-redhat
---
{{- if and .Values.logging.enabled .Values.logging.loki.enabled }}
apiVersion: v1
kind: Namespace
metadata:
  name: openshift-logging
---
{{- end }}
{{- if .Values.metrics.enabled }}
apiVersion: v1
kind: Namespace
metadata:
  name: open-cluster-management-observability
{{- end }}