apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: policy-hub-grafana
  namespace: default
spec:
  disabled: false
  policy-templates:
  - objectDefinition:
      apiVersion: policy.open-cluster-management.io/v1
      kind: ConfigurationPolicy
      metadata:
        name: community-grafana
      spec:
        remediationAction: enforce
        severity: high
        pruneObjectBehavior: DeleteAll
        object-templates:
          - complianceType: musthave
            objectDefinition:
              apiVersion: v1
              kind: Namespace
              metadata:
                name: grafana-operator
          - complianceType: musthave
            objectDefinition:
              apiVersion: operators.coreos.com/v1
              kind: OperatorGroup
              metadata:
                name: grafana-operator-kz2v9
                namespace: grafana-operator
                annotations:
                  olm.providedAPIs: Grafana.v1beta1.grafana.integreatly.org,GrafanaDashboard.v1beta1.grafana.integreatly.org,GrafanaDatasource.v1beta1.grafana.integreatly.org,GrafanaFolder.v1beta1.grafana.integreatly.org
              spec:
                upgradeStrategy: Default
          - complianceType: musthave
            objectDefinition:
              apiVersion: operators.coreos.com/v1alpha1
              kind: Subscription
              metadata:
                name: grafana-operator
                namespace: grafana-operator
                labels:
                  operators.coreos.com/grafana-operator.grafana-operator: ""
              spec:
                name: grafana-operator
                channel: v5
                installPlanApproval: Automatic
                source: community-operators
                sourceNamespace: openshift-marketplace
                startingCSV: grafana-operator.v5.6.3
  - extraDependencies:
    - apiVersion: policy.open-cluster-management.io/v1
      compliance: Compliant
      kind: ConfigurationPolicy
      name: community-grafana
    - apiVersion: policy.open-cluster-management.io/v1
      compliance: Compliant
      kind: ConfigurationPolicy
      name: signals-auth-copy
    objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: grafana-instance
        spec:
          remediationAction: enforce
          severity: high
          pruneObjectBehavior: DeleteAll
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: grafana.integreatly.org/v1beta1
                kind: Grafana
                metadata:
                  name: grafana
                  namespace: grafana-operator
                  labels:
                    dashboards: grafana
                spec:
                  config:
                    auth:
                      disable_login_form: "false"
                    log:
                      mode: console
                    security:
                      admin_password: secret
                      admin_user: root
                  route:
                    spec: {}
            - complianceType: musthave
              objectDefinition:
                apiVersion: grafana.integreatly.org/v1beta1
                kind: GrafanaDatasource
                metadata:
                  name: grafana-loki-datasource
                  namespace: grafana-operator
                spec:
                  datasource:
                    name: loki
                    access: proxy
                    editable: true
                    isDefault: true
                    jsonData:
                      timeInterval: 5s
                      tlsAuth: true
                      tlsAuthWithCACert: true
                      tlsSkipVerify: false
                    secureJsonData:
                      tlsCACert: ${service-ca.crt}
                      tlsClientCert: ${tls.crt}
                      tlsClientKey: ${tls.key}
                    type: loki
                    url: https://lokistack-hub-gateway-http.openshift-logging.svc:8080/api/logs/v1/spoke-1/
                  instanceSelector:
                    matchLabels:
                      dashboards: grafana
                  valuesFrom:
                    - targetPath: secureJsonData.tlsCACert
                      valueFrom:
                        configMapKeyRef:
                          name: lokistack-hub-gateway-ca-bundle
                          key: service-ca.crt
                    - targetPath: secureJsonData.tlsClientCert
                      valueFrom:
                        secretKeyRef:
                          name: loki-admin
                          key: tls.crt
                    - targetPath: secureJsonData.tlsClientKey
                      valueFrom:
                        secretKeyRef:
                          name: loki-admin
                          key: tls.key
            - complianceType: musthave
              objectDefinition:
                apiVersion: grafana.integreatly.org/v1beta1
                kind: GrafanaDatasource
                metadata:
                  name: grafana-thanos-datasource
                  namespace: grafana-operator
                spec:
                  datasource:
                    name: thanos
                    access: proxy
                    editable: true
                    isDefault: true
                    jsonData:
                      timeInterval: 5s
                      tlsAuth: true
                      tlsAuthWithCACert: false
                      tlsSkipVerify: true
                    secureJsonData:
                      tlsCACert: ${ca.crt}
                      tlsClientCert: ${tls.crt}
                      tlsClientKey: ${tls.key}
                    type: prometheus
                    url: https://observability-observatorium-api.open-cluster-management-observability.svc.cluster.local:8080/api/metrics/v1/default
                  instanceSelector:
                    matchLabels:
                      dashboards: grafana
                  valuesFrom:
                    - targetPath: secureJsonData.tlsCACert
                      valueFrom:
                        secretKeyRef:
                          name: observability-server-certs
                          key: ca.crt
                    - targetPath: secureJsonData.tlsClientCert
                      valueFrom:
                        secretKeyRef:
                          name: observability-grafana-certs
                          key: tls.crt
                    - targetPath: secureJsonData.tlsClientKey
                      valueFrom:
                        secretKeyRef:
                          name: observability-grafana-certs
                          key: tls.key
            - complianceType: musthave
              objectDefinition:
                apiVersion: grafana.integreatly.org/v1beta1
                kind: GrafanaDashboard
                metadata:
                  name: mcoa-dashboard
                  namespace: grafana-operator
                spec:
                  instanceSelector:
                    matchLabels:
                      dashboards: "grafana"
                  configMapRef:
                    name: mcoa-dashboard
                    key: json
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1
                kind: ConfigMap
                metadata:
                  name: mcoa-dashboard
                  namespace: grafana-operator
                data:
                  json: >
                    {
                      "annotations": {
                        "list": [
                          {
                            "builtIn": 1,
                            "datasource": {
                              "type": "grafana",
                              "uid": "-- Grafana --"
                            },
                            "enable": true,
                            "hide": true,
                            "iconColor": "rgba(0, 211, 255, 1)",
                            "name": "Annotations & Alerts",
                            "target": {
                              "limit": 100,
                              "matchAny": false,
                              "tags": [],
                              "type": "dashboard"
                            },
                            "type": "dashboard"
                          }
                        ]
                      },
                      "editable": true,
                      "fiscalYearStartMonth": 0,
                      "graphTooltip": 0,
                      "id": 5,
                      "links": [],
                      "liveNow": false,
                      "panels": [
                        {
                          "datasource": {
                            "type": "prometheus",
                            "uid": "abdc028b-0c2c-4416-a2d2-d8ea61dcd4bc"
                          },
                          "fieldConfig": {
                            "defaults": {
                              "color": {
                                "mode": "palette-classic"
                              },
                              "custom": {
                                "axisCenteredZero": false,
                                "axisColorMode": "text",
                                "axisLabel": "",
                                "axisPlacement": "auto",
                                "barAlignment": 0,
                                "drawStyle": "line",
                                "fillOpacity": 0,
                                "gradientMode": "none",
                                "hideFrom": {
                                  "legend": false,
                                  "tooltip": false,
                                  "viz": false
                                },
                                "lineInterpolation": "linear",
                                "lineWidth": 1,
                                "pointSize": 5,
                                "scaleDistribution": {
                                  "type": "linear"
                                },
                                "showPoints": "auto",
                                "spanNulls": false,
                                "stacking": {
                                  "group": "A",
                                  "mode": "none"
                                },
                                "thresholdsStyle": {
                                  "mode": "off"
                                }
                              },
                              "mappings": [],
                              "thresholds": {
                                "mode": "absolute",
                                "steps": [
                                  {
                                    "color": "green",
                                    "value": null
                                  },
                                  {
                                    "color": "red",
                                    "value": 80
                                  }
                                ]
                              }
                            },
                            "overrides": []
                          },
                          "gridPos": {
                            "h": 8,
                            "w": 12,
                            "x": 0,
                            "y": 0
                          },
                          "id": 2,
                          "options": {
                            "legend": {
                              "calcs": [],
                              "displayMode": "list",
                              "placement": "bottom",
                              "showLegend": true
                            },
                            "tooltip": {
                              "mode": "single",
                              "sort": "none"
                            }
                          },
                          "targets": [
                            {
                              "datasource": {
                                "type": "prometheus",
                                "uid": "c48de94c-4781-454e-9afa-bc98bc055fca"
                              },
                              "editorMode": "builder",
                              "expr": "sum by(clusterID, namespace) (namespace:container_memory_usage_bytes:sum{namespace=\"openshift-console-operator\"})",
                              "key": "Q-bc53f8ac-3df1-476e-83f3-c1bed492a796-0",
                              "range": true,
                              "refId": "Console Memory"
                            }
                          ],
                          "title": "Sum container memory usage",
                          "type": "timeseries"
                        },
                        {
                          "datasource": {
                            "type": "loki",
                            "uid": "9a70b20e-8abe-4394-b428-636ce3c078e7"
                          },
                          "fieldConfig": {
                            "defaults": {
                              "color": {
                                "mode": "palette-classic"
                              },
                              "custom": {
                                "axisCenteredZero": false,
                                "axisColorMode": "text",
                                "axisLabel": "",
                                "axisPlacement": "auto",
                                "barAlignment": 0,
                                "drawStyle": "bars",
                                "fillOpacity": 100,
                                "gradientMode": "hue",
                                "hideFrom": {
                                  "legend": false,
                                  "tooltip": false,
                                  "viz": false
                                },
                                "lineInterpolation": "linear",
                                "lineWidth": 8,
                                "pointSize": 5,
                                "scaleDistribution": {
                                  "type": "linear"
                                },
                                "showPoints": "auto",
                                "spanNulls": false,
                                "stacking": {
                                  "group": "A",
                                  "mode": "none"
                                },
                                "thresholdsStyle": {
                                  "mode": "off"
                                }
                              },
                              "mappings": [],
                              "thresholds": {
                                "mode": "absolute",
                                "steps": [
                                  {
                                    "color": "green",
                                    "value": null
                                  },
                                  {
                                    "color": "red",
                                    "value": 80
                                  }
                                ]
                              }
                            },
                            "overrides": []
                          },
                          "gridPos": {
                            "h": 8,
                            "w": 12,
                            "x": 0,
                            "y": 8
                          },
                          "id": 3,
                          "options": {
                            "legend": {
                              "calcs": [],
                              "displayMode": "list",
                              "placement": "bottom",
                              "showLegend": true
                            },
                            "tooltip": {
                              "mode": "single",
                              "sort": "none"
                            }
                          },
                          "pluginVersion": "9.1.6",
                          "targets": [
                            {
                              "datasource": {
                                "type": "loki",
                                "uid": "9a70b20e-8abe-4394-b428-636ce3c078e7"
                              },
                              "editorMode": "builder",
                              "expr": "sum by(namespace, clusterID) (rate({kubernetes_namespace_name=\"openshift-console-operator\"} |= `` | label_format namespace=kubernetes_namespace_name | label_format clusterID=openshift_cluster_id [$__interval]))",
                              "key": "Q-e99c1178-1445-48a9-b847-9e87abedded1-0",
                              "queryType": "range",
                              "refId": "Console Logs Sum"
                            }
                          ],
                          "title": "Console Logs",
                          "type": "timeseries"
                        }
                      ],
                      "refresh": false,
                      "schemaVersion": 37,
                      "style": "dark",
                      "tags": [],
                      "templating": {
                        "list": []
                      },
                      "time": {
                        "from": "now-5m",
                        "to": "now"
                      },
                      "timepicker": {},
                      "timezone": "",
                      "title": "MCOA",
                      "uid": "CuUyrZTSz",
                      "version": 4,
                      "weekStart": ""
                    }