{{- if and .Values.tracing.enabled }}
apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: policy-hub-otel-operator
spec:
  disabled: false
  policy-templates:
  - objectDefinition:
      apiVersion: policy.open-cluster-management.io/v1
      kind: ConfigurationPolicy
      metadata:
        name: redhat-openshift-otel-operator
      spec:
        remediationAction: enforce
        severity: high
        pruneObjectBehavior: DeleteAll
        object-templates:
        - complianceType: musthave
          objectDefinition:
            apiVersion: v1
            kind: Namespace
            metadata:
              name: openshift-opentelemetry-operator
        - complianceType: musthave
          objectDefinition:
            apiVersion: operators.coreos.com/v1
            kind: OperatorGroup
            metadata:
              name: openshift-opentelemetry-operator
              namespace: openshift-opentelemetry-operator
            spec:
              targetNamespaces:
              - openshift-opentelemetry-operator
              upgradeStrategy: Default
        - complianceType: musthave
          objectDefinition:
            apiVersion: operators.coreos.com/v1alpha1
            kind: Subscription
            metadata:
              name: opentelemetry-product
              namespace: openshift-opentelemetry-operator
            spec:
              channel: stable
              installPlanApproval: Automatic
              name: opentelemetry-product
              source: redhat-operators
              sourceNamespace: openshift-marketplace
{{- end }}