apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: open-cluster-management:mcoa-addon:klusterlet-work:agent
  labels:
    app: {{ template "mcoahelm.name" . }}
    chart: {{ template "mcoahelm.chart" . }}
    release: {{ .Release.Name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: open-cluster-management:multicluster-observability-addon:klusterlet-work:agent
subjects:
  - kind: ServiceAccount
    name: klusterlet-work-sa
    namespace: open-cluster-management-agent
