{{- if .Values.logging.enabled }}
{{- range $_, $cluster_name := .Values.spokeClusters }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: logging-{{ $cluster_name }}
  namespace: {{ $cluster_name }}
  labels:
    mcoa.openshift.io/signal: logging
data:
{{- range $_, $dic := $.Values.logging.outputs }}
{{- if eq $dic.type "cloudwatch" }}
  {{ $dic.name }}: StaticAuthentication
{{- end }}
{{- if eq $dic.type "loki" }}
  {{ $dic.name }}: mTLS
{{- end }}
{{- end }}
---
{{- end }}
{{- end }}