apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: open-cluster-management:klusterlet-work:my-role
  labels:
    open-cluster-management.io/aggregate-to-work: "true"
rules:
  - apiGroups: ["project.openshift.io"]
    resources: ["projects"]
    verbs: ["get", "create", "update", "patch", "delete"]
