{{- if .Values.instrumentationEnabled }}
apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: mcoa-instance
  namespace: mcoa-opentelemetry
  labels:
    app: {{ template "tracinghelm.name" . }}
    chart: {{ template "tracinghelm.chart" . }}
    release: {{ .Release.Name }}
spec:
{{- fromJson .Values.instrumentationSpec | toYaml | nindent 2 }}
{{- end }}