{{- if .Values.enabled }}
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: openshift-opentelemetry-operator-ghl6v
  namespace: openshift-opentelemetry-operator
  labels:
    app: {{ template "tracinghelm.name" . }}
    chart: {{ template "tracinghelm.chart" . }}
    release: {{ .Release.Name }}
spec:
  upgradeStrategy: Default
{{- end }}