{{- if .Values.enabled }}
apiVersion: project.openshift.io/v1
kind: Project
metadata:
  name: openshift-opentelemetry-operator
  labels:
    app: {{ template "tracinghelm.name" . }}
    chart: {{ template "tracinghelm.chart" . }}
    release: {{ .Release.Name }}
---
apiVersion: project.openshift.io/v1
kind: Project
metadata:
  name: spoke-otelcol
  labels:
    app: {{ template "tracinghelm.name" . }}
    chart: {{ template "tracinghelm.chart" . }}
    release: {{ .Release.Name }}
{{- end }}
